-- NB: NoImplicitPrelude is active from cabal common-options.
--
-- Artifact generators that consume a 'SystemSpec'.  None of these functions
-- are in the Clash synthesis path; they may use 'String', lists, 'IO', etc.
module Isacle.System.Generate
    ( extractMemoryMap
    , genCHeader
    , genLinkerScript
    ) where

import Prelude
import Data.Char (toUpper)
import Data.List (intercalate, sortBy)
import Data.Ord (comparing)
import Data.Word (Word32)
import Numeric (showHex)

import Isacle.System.Spec

-- ---------------------------------------------------------------------------
-- Helpers
-- ---------------------------------------------------------------------------

hex32 :: Word32 -> String
hex32 w = "0x" ++ pad (showHex w "")
  where pad s = replicate (8 - length s) '0' ++ s

padRight :: Int -> String -> String
padRight n s = s ++ replicate (max 0 (n - length s)) ' '

compBase :: ComponentSpec -> Word32
compBase (SpecROM b _ _)    = b
compBase (SpecRAM b _ _ _)  = b
compBase (SpecPeriph b _ _ _) = b
compBase _                  = maxBound

isMem :: ComponentSpec -> Bool
isMem SpecROM{}    = True
isMem SpecRAM{}    = True
isMem SpecPeriph{} = True
isMem _            = False

isPort :: ComponentSpec -> Bool
isPort SpecPort{} = True
isPort _          = False

-- ---------------------------------------------------------------------------
-- extractMemoryMap
-- ---------------------------------------------------------------------------

-- | Human-readable memory map table.
--
-- Example output:
--
-- > MEMORY MAP
-- > ==========
-- > Base         End          Size         Name
-- > ------------------------------------------------------------
-- > 0x00000000   0x00001FFF   0x00002000   code (ROM)
-- > 0x00001000   0x000017FF   0x00000800   ram  (RAM)
-- > 0x00000300   0x00000307   0x00000008   uart (peripheral)
-- > 0x00000500   0x0000050F   0x00000010   gpio (peripheral)
-- >
-- > PORTS
-- > =====
-- > uart_rx              PIn  (1-bit)
-- > uart_tx              POut (1-bit)
-- >
-- > CPU: AVR clavr
extractMemoryMap :: SystemSpec -> String
extractMemoryMap spec = unlines $ concat
    [ header
    , map renderMem (sortBy (comparing compBase) memComps)
    , portSection
    , cpuSection
    ]
  where
    comps    = ssComponents spec
    memComps = filter isMem comps
    portComps = filter isPort comps
    cpuNames  = [n | SpecCPU n <- comps]

    col = 13
    header =
        [ "MEMORY MAP"
        , "=========="
        , padRight col "Base" ++ padRight col "End" ++ padRight col "Size" ++ "Name"
        , replicate 65 '-'
        ]

    renderMem (SpecROM b sz n) =
        padRight col (hex32 b) ++ padRight col (hex32 (b + sz - 1)) ++
        padRight col (hex32 sz) ++ n ++ " (ROM)"
    renderMem (SpecRAM b sz n _) =
        padRight col (hex32 b) ++ padRight col (hex32 (b + sz - 1)) ++
        padRight col (hex32 sz) ++ n ++ " (RAM)"
    renderMem (SpecPeriph b sz n _) =
        padRight col (hex32 b) ++ padRight col (hex32 (b + sz - 1)) ++
        padRight col (hex32 sz) ++ n ++ " (peripheral)"
    renderMem _ = ""

    portSection
        | null portComps = []
        | otherwise = "" : "PORTS" : "=====" : map renderPort portComps

    renderPort (SpecPort n d w) =
        padRight 21 n ++ padRight 6 (show d) ++ "(" ++ showWidth w ++ ")"
    renderPort _ = ""

    showWidth PW1  = "1-bit"
    showWidth PW8  = "8-bit"
    showWidth PW16 = "16-bit"
    showWidth PW32 = "32-bit"

    cpuSection
        | null cpuNames = []
        | otherwise     = ["", "CPU: " ++ intercalate ", " cpuNames]

-- ---------------------------------------------------------------------------
-- genCHeader
-- ---------------------------------------------------------------------------

-- | Generate a C header defining @BASE@ and @SIZE@ macros for every
--   memory-mapped component.
--
-- @guardName@ becomes the include guard (converted to upper-case, @_H@ appended).
--
-- Example (@guardName = "memmap"@):
--
-- > /* Auto-generated by ISACLE */
-- > #ifndef MEMMAP_H
-- > #define MEMMAP_H
-- >
-- > #define CODE_BASE  0x00000000UL
-- > #define CODE_SIZE  0x00002000UL
-- > #define RAM_BASE   0x00001000UL
-- > ...
-- > #endif /* MEMMAP_H */
genCHeader :: String -> SystemSpec -> String
genCHeader guardName spec = unlines $
    [ "/* Auto-generated by ISACLE */"
    , "#ifndef " ++ guard
    , "#define " ++ guard
    , ""
    ]
    ++ concatMap renderComp memComps
    ++
    [ ""
    , "#endif /* " ++ guard ++ " */"
    ]
  where
    guard    = map toUpper guardName ++ "_H"
    memComps = filter isMem (ssComponents spec)
    up       = map toUpper
    hexUL w  = "0x" ++ map toUpper (showHex w "") ++ "UL"

    renderComp (SpecROM b sz n) =
        [ "#define " ++ up n ++ "_BASE  " ++ hexUL b
        , "#define " ++ up n ++ "_SIZE  " ++ hexUL sz
        ]
    renderComp (SpecRAM b sz n _) =
        [ "#define " ++ up n ++ "_BASE  " ++ hexUL b
        , "#define " ++ up n ++ "_SIZE  " ++ hexUL sz
        ]
    renderComp (SpecPeriph b sz n _) =
        [ "#define " ++ up n ++ "_BASE  " ++ hexUL b
        , "#define " ++ up n ++ "_SIZE  " ++ hexUL sz
        ]
    renderComp _ = []

-- ---------------------------------------------------------------------------
-- genLinkerScript
-- ---------------------------------------------------------------------------

-- | Generate a GNU LD linker script with MEMORY and SECTIONS directives.
--
-- All 'SpecROM' components become @(rx)@ regions; all 'SpecRAM' components
-- become @(rwx)@ regions.  Standard ELF sections are mapped to the first ROM
-- (read-only) and first RAM (writable) found in the spec.
--
-- Example:
--
-- > MEMORY {
-- >   code (rx)  : ORIGIN = 0x0, LENGTH = 0x2000
-- >   ram  (rwx) : ORIGIN = 0x1000, LENGTH = 0x800
-- > }
-- >
-- > SECTIONS {
-- >   .text   : { *(.text*)   } > code
-- >   .rodata : { *(.rodata*) } > code
-- >   .data   : { *(.data*)   } > ram AT > code
-- >   .bss    : { *(.bss*)    } > ram
-- > }
genLinkerScript :: SystemSpec -> String
genLinkerScript spec = unlines $
    [ "/* Auto-generated by ISACLE */"
    , "MEMORY {"
    ]
    ++ map renderRegion (sortBy (comparing compBase) (romComps ++ ramComps))
    ++
    [ "}"
    , ""
    , "SECTIONS {"
    , "  .text   : { *(.text*)   } > " ++ romReg
    , "  .rodata : { *(.rodata*) } > " ++ romReg
    , "  .data   : { *(.data*)   } > " ++ ramReg ++ " AT > " ++ romReg
    , "  .bss    : { *(.bss*)    } > " ++ ramReg
    , "}"
    ]
  where
    comps   = ssComponents spec
    romComps = [c | c@SpecROM{} <- comps]
    ramComps = [c | c@SpecRAM{} <- comps]

    romReg = case romComps of (SpecROM _ _ n : _) -> n; _ -> "rom"
    ramReg = case ramComps of (SpecRAM _ _ n _ : _) -> n; _ -> "ram"

    hexLen w = "0x" ++ showHex w ""

    renderRegion (SpecROM b sz n) =
        "  " ++ padRight 8 n ++ "(rx)  : ORIGIN = " ++ hexLen b ++ ", LENGTH = " ++ hexLen sz
    renderRegion (SpecRAM b sz n _) =
        "  " ++ padRight 8 n ++ "(rwx) : ORIGIN = " ++ hexLen b ++ ", LENGTH = " ++ hexLen sz
    renderRegion _ = ""
